### ISSUE TITLE
Crashing on checking in Homekit

### ISSUE THREAD

**Issue by JimmyEyeball** [grzegorz914/homebridge-xbox-tv#14]
First of all, I see this plugin has only been updated today so not sure if it's related as I am a new user of this plugin today...

Looks to be connecting fine when watching logs but as soon as I go to Homekit Device in homekit goes straight to "updating" then home bridge crash. I have tried with all the default apps included with exactly the same result...

Any suggestions...

I am also swapping over from (homebridge-smartglass) but this has been fully removed....

[4/28/2020, 19:37:56] Homebridge is running on port 44455.
Apr 28 19:37:56 raspberrypi homebridge[2610]: [4/28/2020, 19:37:56] [XboxTv] prepareTelevisionService
Apr 28 19:37:56 raspberrypi homebridge[2610]: [4/28/2020, 19:37:56] [XboxTv] prepareSpeakerService
Apr 28 19:37:56 raspberrypi homebridge[2610]: [4/28/2020, 19:37:56] [XboxTv] prepareInputsService
Apr 28 19:37:56 raspberrypi homebridge[2610]: [4/28/2020, 19:37:56] [XboxTv] Device: 192.168.1.27, apps file does not exist
Apr 28 19:37:56 raspberrypi homebridge[2610]: [4/28/2020, 19:37:56] [XboxTv] Device: 192.168.1.27, publishExternalAccessories: LIVINGROOM-XBOX
Apr 28 19:37:56 raspberrypi homebridge[2610]: [4/28/2020, 19:37:56] LIVINGROOM-XBOX is running on port 40797.
Apr 28 19:37:56 raspberrypi homebridge[2610]: [4/28/2020, 19:37:56] Please add [LIVINGROOM-XBOX] manually in Home app. Setup Code: 999-99-999
Apr 28 19:38:03 raspberrypi homebridge[2610]: [4/28/2020, 19:38:03] [XboxTv] Device: 192.168.1.27, name: LIVINGROOM-XBOX, state: Online
Apr 28 19:38:05 raspberrypi homebridge[2610]: [4/28/2020, 19:38:05] ReferenceError: getCharacteristic is not defined
Apr 28 19:38:05 raspberrypi homebridge[2610]:     at xboxTvDevice.getApp (/usr/local/lib/node_modules/homebridge-xbox-tv/index.js:393:6)
Apr 28 19:38:05 raspberrypi homebridge[2610]:     at ActiveIdentifier.emit (events.js:223:5)
Apr 28 19:38:05 raspberrypi homebridge[2610]:     at ActiveIdentifier.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
Apr 28 19:38:05 raspberrypi homebridge[2610]:     at ActiveIdentifier.Characteristic._this.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:451:12)
Apr 28 19:38:05 raspberrypi homebridge[2610]:     at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1180:22
Apr 28 19:38:05 raspberrypi homebridge[2610]:     at Array.forEach (<anonymous>)
Apr 28 19:38:05 raspberrypi homebridge[2610]:     at Accessory._this._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1108:10)
Apr 28 19:38:05 raspberrypi homebridge[2610]:     at HAPServer.emit (events.js:223:5)
Apr 28 19:38:05 raspberrypi homebridge[2610]:     at HAPServer.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
Apr 28 19:38:05 raspberrypi homebridge[2610]:     at HAPServer._this._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:900:12)
Apr 28 19:38:05 raspberrypi homebridge[2610]: [4/28/2020, 19:38:05] Got SIGTERM, shutting down Homebridge...

	"description": "XBOX",

	"platforms": [{
		"platform": "XboxTv",
		"devices": [{
			"name": "LIVINGROOM-XBOX",
			"host": "192.168.1.27",
			"xboxliveid": "FD0068E701A2xxxx",
			"volumeControl": false,
			"switchInfoMenu": false,
			"apps": [{
					"name": "TV",
					"reference": "Microsoft.Xbox.LiveTV_8wekyb3d8bbwe!Microsoft.Xbox.LiveTV.Application"
				},
				{
					"name": "Dashboard",
					"reference": "Xbox.Dashboard_8wekyb3d8bbwe!Xbox.Dashboard.Application"
				},
				{
					"name": "Youtube",
					"reference": "GoogleInc.YouTube_yfg5n0ztvskxp!App"
				},
				{
					"name": "Netflix",
					"reference": "4DF9E0F8.Netflix_mcm4njqhnhss8!App"
				}
			]
		}]
	}],
	"accessories": []
}

**Comment by JimmyEyeball** [comment]
Apr 28 19:56:53 raspberrypi homebridge[4511]: [4/28/2020, 19:56:53] Homebridge is running on port 44455.
Apr 28 19:56:53 raspberrypi homebridge[4511]: [4/28/2020, 19:56:53] [XboxTv] prepareTelevisionService
Apr 28 19:56:53 raspberrypi homebridge[4511]: [4/28/2020, 19:56:53] [XboxTv] prepareSpeakerService
Apr 28 19:56:53 raspberrypi homebridge[4511]: [4/28/2020, 19:56:53] [XboxTv] prepareInputsService
Apr 28 19:56:53 raspberrypi homebridge[4511]: [4/28/2020, 19:56:53] [XboxTv] Device: 192.168.1.27, apps file does not exist
Apr 28 19:56:53 raspberrypi homebridge[4511]: [4/28/2020, 19:56:53] [XboxTv] prepareVolumeService
Apr 28 19:56:53 raspberrypi homebridge[4511]: [4/28/2020, 19:56:53] [XboxTv] Device: 192.168.1.27, publishExternalAccessories: LIVINGROOM-XBOX
Apr 28 19:56:53 raspberrypi homebridge[4511]: [4/28/2020, 19:56:53] LIVINGROOM-XBOX is running on port 38991.
Apr 28 19:56:53 raspberrypi homebridge[4511]: [4/28/2020, 19:56:53] Please add [LIVINGROOM-XBOX] manually in Home app. Setup Code: 999-99-999
Apr 28 19:57:01 raspberrypi homebridge[4511]: [4/28/2020, 19:57:01] [XboxTv] Device: 192.168.1.27, name: LIVINGROOM-XBOX, state: Online

**Comment by grzegorz914** [comment]
Bhagwan a version of plugin U use?

**Comment by JimmyEyeball** [comment]
Its the latest version from yesterday...

**Comment by netRunner0** [comment]
![Uploading IMG_0740.jpeg…]()

**Comment by netRunner0** [comment]
![EFA364C1-5778-4883-B3DF-45E381DE1247](https://user-images.githubusercontent.com/44049295/80588716-48a51e00-8a32-11ea-9715-706dcf663f90.jpeg)

**Comment by grzegorz914** [comment]
Ahh, OK I found this, fixed in 0.2.7

**Comment by JimmyEyeball** [comment]
Great job yes getting somewhere now... So all looking good Power ON/Off, Volume, Status all ok but when trying to change apps I am getting the error bellow but I am assuming this is something else altogether Is there a way to pull the app IDs from the Apps on my XBox or are they the only apps you can add to this list.... 


Apr 29 15:12:00 raspberrypi homebridge[1698]: [4/29/2020, 15:12:00] [XboxTv] Device: 192.168.1.27, get current App successful: Xbox.Dashboard_8wekyb3d8bbwe!Xbox.Dashboard.Application
Apr 29 15:12:01 raspberrypi homebridge[1698]: [4/29/2020, 15:12:01] TypeError: Cannot read property '4' of undefined
Apr 29 15:12:01 raspberrypi homebridge[1698]:     at /usr/local/lib/node_modules/homebridge-xbox-tv/index.js:415:42
Apr 29 15:12:01 raspberrypi homebridge[1698]:     at xboxTvDevice.getApp (/usr/local/lib/node_modules/homebridge-xbox-tv/index.js:404:7)
Apr 29 15:12:01 raspberrypi homebridge[1698]:     at xboxTvDevice.setApp (/usr/local/lib/node_modules/homebridge-xbox-tv/index.js:410:6)
Apr 29 15:12:01 raspberrypi homebridge[1698]:     at ActiveIdentifier.emit (events.js:223:5)
Apr 29 15:12:01 raspberrypi homebridge[1698]:     at ActiveIdentifier.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
Apr 29 15:12:01 raspberrypi homebridge[1698]:     at ActiveIdentifier.Characteristic._this.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:614:12)
Apr 29 15:12:01 raspberrypi homebridge[1698]:     at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1441:24
Apr 29 15:12:01 raspberrypi homebridge[1698]:     at Array.forEach (<anonymous>)
Apr 29 15:12:01 raspberrypi homebridge[1698]:     at Accessory._this._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1283:10)
Apr 29 15:12:01 raspberrypi homebridge[1698]:     at HAPServer.emit (events.js:223:5)
Apr 29 15:12:01 raspberrypi homebridge[1698]: [4/29/2020, 15:12:01] Got SIGTERM, shutting down Homebridge...

**Comment by grzegorz914** [comment]
fixed 0.2.8 is ready.

**Comment by JimmyEyeball** [comment]
Yes all looking good now no crashing at all!!! But... there is no response at all when trying to change input and volume .....

**Comment by grzegorz914** [comment]
Absolute volume control using slider is not possible, I have add this but right now the api does not contain this feature, U can disable this in config.json and use hardware button on iPhone to change the volume. Als switch to specific app is not possible, the api does not have this Feature, U can only see on which app actually is the console. I think it I clear now.

**Comment by JimmyEyeball** [comment]
OK Great then working as it should be... I have disabled volume control this has removed the slider but still not changing the volume even with the hardware buttons but this isn't a big deal anyway...

Is there any way of pulling the IDs for other apps from the console to add to this list?

**Comment by grzegorz914** [comment]
The volume with hardware button changed after U go to RC control app on iPhone and select Xbox

**Comment by JimmyEyeball** [comment]
Not sure if this is update related but I'm getting the error below today...


 [4/30/2020, 22:56:49] Please add [LIVINGROOM-XBOX] manually in Home app. Setup Code: 999-99-999
Apr 30 22:56:56 raspberrypi homebridge[2130]: [4/30/2020, 22:56:56] [XboxTv] Device: 192.168.1.27, name: LIVINGROOM-XBOX, state: Online
Apr 30 22:56:56 raspberrypi homebridge[2130]: [4/30/2020, 22:56:56] TypeError: Cannot read property 'indexOf' of undefined
Apr 30 22:56:56 raspberrypi homebridge[2130]:     at xboxTvDevice.<anonymous> (/usr/local/lib/node_modules/homebridge-xbox-tv/index.js:143:49)
Apr 30 22:56:56 raspberrypi homebridge[2130]:     at EventEmitter.emit (events.js:228:7)
Apr 30 22:56:56 raspberrypi homebridge[2130]:     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/homebridge-xbox-tv/node_modules/xbox-smartglass-core-node/src/events.js:116:27)
Apr 30 22:56:56 raspberrypi homebridge[2130]:     at EventEmitter.emit (events.js:223:5)
Apr 30 22:56:56 raspberrypi homebridge[2130]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-xbox-tv/node_modules/xbox-smartglass-core-node/src/smartglass.js:324:30)
Apr 30 22:56:56 raspberrypi homebridge[2130]:     at Socket.emit (events.js:223:5)
Apr 30 22:56:56 raspberrypi homebridge[2130]:     at UDP.onMessage (dgram.js:874:8)
Apr 30 22:56:56 raspberrypi homebridge[2130]: [4/30/2020, 22:56:56] Got SIGTERM, shutting down Homebridge...
Apr 30 22:57:01 raspberrypi systemd[1]: homebridgeXbox.service: Main process exited, code=exited, status=143/n/a
Apr 30 22:57:01 raspberrypi systemd[1]: homebridgeXbox.service: Unit entered failed state.
Apr 30 22:57:01 raspberrypi systemd[1]: homebridgeXbox.service: Failed with result 'exit-code'.
Apr 30 22:57:11 raspberrypi systemd[1]: homebridgeXbox.service: Service hold-off time over, scheduling restart.
Apr 30 22:57:11 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.

**Comment by grzegorz914** [comment]
foxed
